### ISSUE TITLE
Configuration flow cannot be started

### ISSUE THREAD

**Issue by FernandoKummer** [djerik/dagen-ha#6]
Hi,

I wanted to configure the integration.
But I always get the following error:

```
Fehler
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}
```

Thanks for your help.

**Comment by djerik** [comment]
Sorry, version 1.0.3 contained incorrect import statement. Please update to 1.0.5

**Comment by FernandoKummer** [comment]
It works perfectly with version 1.0.5. Thanks for your fast help!
